# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
schema = "private"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
except_custom_type_definitions = ["Tsvector"]
import_types = ["diesel::sql_types::*", "diesel_full_text_search::Tsvector"]


[migrations_directory]
dir = "migrations"
